"""sync full rpg user model

Revision ID: 010512ffbc60
Revises: e9978e12c73b
Create Date: 2026-03-05 13:10:09.681318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010512ffbc60'
down_revision: Union[str, Sequence[str], None] = 'e9978e12c73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('character_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('badges', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('titles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('equipped_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_customization', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_customization')
    op.drop_column('users', 'equipped_title')
    op.drop_column('users', 'titles')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'character_level')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
