"""add monthly champion table

Revision ID: 2a05591d52e5
Revises: cb0127271e7d
Create Date: 2026-03-06 07:10:38.196232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a05591d52e5'
down_revision: Union[str, Sequence[str], None] = 'cb0127271e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('character_class', sa.String(), nullable=True),
    sa.Column('character_level', sa.Integer(), nullable=True),
    sa.Column('rewards_granted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_champions_id'), 'monthly_champions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_champions_id'), table_name='monthly_champions')
    op.drop_table('monthly_champions')
    # ### end Alembic commands ###
