"""sync full rpg user model

Revision ID: 2a420245f56a
Revises: 6fe6496afaf3
Create Date: 2026-03-06 08:17:24.156561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a420245f56a'
down_revision: Union[str, Sequence[str], None] = '6fe6496afaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_customization', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('unlocked_colors', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('unlocked_backgrounds', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unlocked_backgrounds')
    op.drop_column('users', 'unlocked_colors')
    op.drop_column('users', 'avatar_customization')
    # ### end Alembic commands ###
