"""add show_briefing to users

Revision ID: 5ef040d3638b
Revises: 63dbda8b9dcc
Create Date: 2026-03-06 11:36:55.454583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef040d3638b'
down_revision: Union[str, Sequence[str], None] = '63dbda8b9dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.add_column('users', sa.Column('show_briefing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_briefing')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
