"""add is_hidden to achievements

Revision ID: 63dbda8b9dcc
Revises: 0ceda4adaaa3
Create Date: 2026-03-06 10:31:45.229724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63dbda8b9dcc'
down_revision: Union[str, Sequence[str], None] = '0ceda4adaaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'is_hidden')
    # ### end Alembic commands ###
