"""update suggestions for status and responses

Revision ID: 6fe6496afaf3
Revises: 2a05591d52e5
Create Date: 2026-03-06 07:13:31.808044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe6496afaf3'
down_revision: Union[str, Sequence[str], None] = '2a05591d52e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('suggestions', sa.Column('admin_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'admin_response')
    op.drop_column('suggestions', 'status')
    # ### end Alembic commands ###
