"""add achievement claiming and titles

Revision ID: 9a8c41a3931e
Revises: 010512ffbc60
Create Date: 2026-03-05 13:11:11.565219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8c41a3931e'
down_revision: Union[str, Sequence[str], None] = '010512ffbc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('title_reward', sa.String(), nullable=True))
    op.add_column('user_achievements', sa.Column('is_claimed', sa.Boolean(), nullable=True))
    op.add_column('user_achievements', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_achievements', 'claimed_at')
    op.drop_column('user_achievements', 'is_claimed')
    op.drop_column('achievements', 'title_reward')
    # ### end Alembic commands ###
