"""sync full rpg user model

Revision ID: b498bdcf9277
Revises: f8227638a604
Create Date: 2026-03-06 04:34:54.242026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b498bdcf9277'
down_revision: Union[str, Sequence[str], None] = 'f8227638a604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('special_effects', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'avatar_customization')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'avatar_state')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('badges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_customization', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'special_effects')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'login_streak')
    # ### end Alembic commands ###
