"""add avatar fields

Revision ID: bb660ed40439
Revises: c154a530f9b4
Create Date: 2026-03-05 12:24:09.781235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb660ed40439'
down_revision: Union[str, Sequence[str], None] = 'c154a530f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_state')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
