"""update conversations for feedback and projects

Revision ID: cb0127271e7d
Revises: 18baf18ddf2a
Create Date: 2026-03-06 06:08:21.254004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0127271e7d'
down_revision: Union[str, Sequence[str], None] = '18baf18ddf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('feedback', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('feedback_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'feedback_notes')
    op.drop_column('conversations', 'feedback')
    op.drop_column('conversations', 'project_id')
    # ### end Alembic commands ###
