"""add personality modes

Revision ID: e9978e12c73b
Revises: 7ee60e4e28c8
Create Date: 2026-03-05 12:50:48.313452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9978e12c73b'
down_revision: Union[str, Sequence[str], None] = '7ee60e4e28c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unlock_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('example_tone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_modes_id'), 'personality_modes', ['id'], unique=False)
    op.create_index(op.f('ix_personality_modes_name'), 'personality_modes', ['name'], unique=True)
    op.add_column('users', sa.Column('active_personality_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'personality_modes', ['active_personality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_personality_id')
    op.drop_index(op.f('ix_personality_modes_name'), table_name='personality_modes')
    op.drop_index(op.f('ix_personality_modes_id'), table_name='personality_modes')
    op.drop_table('personality_modes')
    # ### end Alembic commands ###
